import time

def info():
    print('=' *51)
    print('                   IFORMAÇÕES             ')
    print('')
    print('1- Você deverá responder as questões com o número\ncorrespondente dela!')
    print('2- Cada questão é conometrada!')
    print('3- Você poderá acabar o quiz a qualquer momento!\nbasta digitar: "fim" em qualquer questão')
    print('4- Você terá acesso aos dados do cliente (dados de\nhierarquia menor)')
    print('')
    print('=' *51)
    print('Criador: Carlos Emanoel')
    print('Data de início: 07/11/2020      sáb.')
    print('=' *51)
    time.sleep(10)
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
